# PersistentVolume para Redis (solo entorno local)
# En producción no se hace uso de este archivo, en lugar de definir un PersistentVolume manualmente,
# Se deja que Kubernetes cree el volumen automáticamente a través de un StorageClass (provisión dinámica).
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv                                  # Nombre del volumen persistente
spec:
  capacity:
    storage: 1Gi                                  # Cantidad de almacenamiento reservado
  accessModes:
    - ReadWriteOnce                               # Solo un nodo puede montar el volumen en modo lectura/escritura
  hostPath:
    path: /tmp/volumes/redis                      # Ruta del host donde se almacenarán los datos
                                                  # Esta ruta debe existir en el host (o será creada).
    type: DirectoryOrCreate                       # Se asegura que la ruta se cree si no existe
  persistentVolumeReclaimPolicy: Retain           # Conserva los datos si se elimina el PVC
  storageClassName: local-path                    # Para uso con Minikube. Cambiar en producción.
