# PersistentVolume estático para Kafka (entorno local)
# En producción no se hace uso de este archivo, en lugar de definir un PersistentVolume manualmente,
# Se deja que Kubernetes cree el volumen automáticamente a través de un StorageClass (provisión dinámica).
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv                            # Nombre del volumen persistente
spec:
  capacity:
    storage: 2Gi                            # Espacio de almacenamiento asignado
  accessModes:
    - ReadWriteOnce                         # Solo un nodo puede montar el volumen en modo escritura
  hostPath:
    path: /tmp/volumes/kafka                # Ruta del host donde se almacenarán los datos
    type: DirectoryOrCreate                 # Crea la ruta si no existe
  persistentVolumeReclaimPolicy: Retain     # Conserva los datos incluso si el PVC se elimina
  storageClassName: local-path              # Para uso con Minikube. Cambiar en producción.
